{"name": "testData[CaseData1]", "status": "broken", "statusDetails": {"message": "KeyError: 'casename'", "trace": "self = <testcase.test_excel.TestCase object at 0x0000018894D32FB0>\nCaseData = {'actualResult': '$..msg', 'caseName': '输入错误的账号', 'datas': '{\"accounts\": \"ass\",\"pwd\": \"123456\",\"type\": \"username\"}', 'expectResult': '登录帐号不存在', ...}\n\n    @pytest.mark.parametrize(\"CaseData\",AllCaseData)\n    def testData(self,CaseData):\n    \n        # 调用动态生成标题\n        # self.__dynmic_title(CaseData)\n>       casename=\"ID({})-({})\".format(CaseData[\"id\"],CaseData[\"casename\"])\nE       KeyError: 'casename'\n\ntest_excel.py:42: KeyError"}, "parameters": [{"name": "CaseData", "value": "{'id': 4, 'caseName': '输入错误的账号', 'url': 'http://shop-xo.hctestedu.com/index.php?s=/api/user/login', 'method': 'post', 'headers': '{\"Content-Type\":\"application/json\"}', 'datas': '{\"accounts\": \"ass\",\"pwd\": \"123456\",\"type\": \"username\"}', 'actualResult': '$..msg', 'expectResult': '登录帐号不存在', 'result': '执行通过', 'response': '{\"msg\":\"登录帐号不存在\",\"code\":-3,\"data\":\"\"}'}"}], "start": 1727245006755, "stop": 1727245006755, "uuid": "16aa0243-aaab-4e27-819d-360224b05abf", "historyId": "9c6ba0b04dab05ade8a988969f6c823c", "testCaseId": "92e66718ddbc07993fbf10087035b16e", "fullName": "test_excel.TestCase#testData", "labels": [{"name": "suite", "value": "test_excel"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "DESKTOP-EA3KTC1"}, {"name": "thread", "value": "18592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_excel"}]}